
[NVG]
	#Allowed Values: NORMAL, BRIGHT
	"PVS-14 Brightness" = "NORMAL"
	#Allowed Values: NORMAL, BRIGHT
	"PVS-23 Brightness" = "NORMAL"
	#Allowed Values: NORMAL, BRIGHT
	"GPNVG Brightness" = "NORMAL"

